#include "DAP_config.h"

PortPin SWDIOPin(PIN_SWDIO, INPUT_PULLUP);
PortPin SWCLKPin(PIN_SWCLK, INPUT_PULLUP);
PortPin TDIPin(PIN_TDI, INPUT);
PortPin TDOPin(PIN_TDO, INPUT);
PortPin nRESETPin(PIN_nRESET, INPUT_PULLUP);

#ifndef PIN_LED_CONNECTED
#define PIN_LED_CONNECTED 0
#endif
LED_CONNECTEDPinType LED_CONNECTEDPin(PIN_LED_CONNECTED, INPUT);
#ifndef PIN_LED_RUNNING
#define PIN_LED_RUNNING 0
#endif
LED_RUNNINGPinType LED_RUNNINGPin(PIN_LED_RUNNING, INPUT);
